Staff:
  Permission: "astaff"
  Stuff:
    Vanish:
      Permission: "astaff.vanish"
      Material: "GOLDEN_HOE"
      Name: "Vanish"
      Lore:
        - "This is a Vanish wand"
      Slot: 5
    RandomTp:
      Permission: "astaff.randomtp"
      Material: "CLOCK"
      Name: "Random Tp"
      Lore:
        - "This is a Random Tp watch"
      Slot: 4
    PlayerViewer:
      Permission: "astaff.playerviewer"
      Material: "BOOK"
      Name: "Player Viewer"
      Lore:
        - "This is a book to inspect the player"
      Slot: 3
    Freeze:
      Permission: "astaff.freeze"
      Material: "PACKED_ICE"
      Name: "Freeze"
      Lore:
        - "This is a ice to freeze player"
      Slot: 2
    XRay:
      Permission: "astaff.xray"
      Material: "DIAMOND_PICKAXE"
      Name: "XRay"
      Lore:
        - "This is a ice to Xray player"
      Slot: 1
    TopLuck:
      Permission: "atopluck"
      Material: "DIAMOND_PICKAXE"
      Name: "TopLuck"
      Lore:
        - "This is a ice to TopLuck player"
      Slot: 0
  PlayerViewer:
    GUI:
      PlayerSkull:
        Slot: 0
      TeleportPlayer:
        Material: "ENDER_PEARL"
        Slot: 1
      Sanction:
        Material: "DIAMOND_AXE"
        Slot: 2
      TopLuck:
        Material: "DIAMOND_PICKAXE"
        Slot: 3
  XRay:
    Blocks:
      - "COBBLESTONE"
TopLuck:
  Permission: "atopluck"
  Webhook:
    Url: ""
    Alert: 7
    Time: 18000
Sanction:
  Permission: "asanction"
  GUI:
    # Every category :
    Chat:
      Permission: "asanction.chat"
      Material: "PAPER"
      Reasons:
        # Every reason :
        Spam:
          Permission: "asanction.chat.spam"
          Slot: 0
          Material: "PAPER"
          Sanction:
            Type: "TEMPMUTE"
            Time: 1D
            Reason: "Spam !"
